"""Week 12: Real YouTube API v3 Integration

Uploads videos to YouTube with Service Account authentication.
BLOCKING synchronous upload (use Task API wrapper for async enqueue).
"""

import os
import logging
import time
import hashlib
from pathlib import Path
from typing import Dict, Optional
import json

logger = logging.getLogger(__name__)


def execute(input_data: Dict, state_dir: Path) -> Dict:
    """Upload video to YouTube via API v3 (Service Account).

    WARNING: This is BLOCKING (synchronous). Caller thread freezes until upload completes.
    Use a Task wrapper (ADR-0695, Phase 4) for async non-blocking enqueue.

    Preconditions:
    - YouTube credentials JSON exists (~/.corvin/youtube-credentials.json)
    - Video file exists
    - google-api-python-client installed

    Returns:
        {
            "task_id": str,
            "video_id": str or None,  # None on failure
            "status": "success" | "failed",  # BLOCKING call completes with final status
            "youtube_url": str or None,
            "upload_progress_percent": float
        }
    """
    video_path = input_data.get("video_path")
    metadata = input_data.get("metadata", {})
    credentials_path = input_data.get("credentials_path", Path.home() / ".corvin" / "youtube-credentials.json")
    
    if not video_path or not Path(video_path).exists():
        raise ValueError(f"Video file not found: {video_path}")
    
    if not Path(credentials_path).exists():
        raise ValueError(f"YouTube credentials not found: {credentials_path}")

    # Generate task ID (SHA256-based, stable, with streaming hash for large files)
    video_file = Path(video_path)

    # FIX: Stream hash instead of reading entire file into memory
    hasher = hashlib.sha256()
    with open(video_file, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            hasher.update(chunk)
    video_hash = hasher.hexdigest()[:8]

    # FIX: Use proper import instead of __import__('time')
    task_id = f"yt_upload_{video_hash}_{int(time.time())}"
    
    try:
        from google.oauth2 import service_account
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload
    except ImportError:
        raise ImportError("google-api-python-client not installed. Install: pip install google-api-python-client google-auth-oauthlib")
    
    # Load credentials
    creds_dict = json.loads(Path(credentials_path).read_text())
    credentials = service_account.Credentials.from_service_account_info(
        creds_dict,
        scopes=['https://www.googleapis.com/auth/youtube.upload']
    )
    
    # Build YouTube API client
    youtube = build('youtube', 'v3', credentials=credentials)
    
    # Prepare upload
    video_file = Path(video_path)
    media_upload = MediaFileUpload(
        str(video_file),
        mimetype='video/mp4',
        resumable=True,
        chunksize=1024 * 1024  # 1 MB chunks
    )
    
    # Video metadata
    body = {
        'snippet': {
            'title': metadata.get('title', 'CorvinOS Video'),
            'description': metadata.get('description', 'Generated by CorvinOS Video Producer'),
            'tags': metadata.get('tags', ['corvinOS', 'video', 'production']),
            'categoryId': '28'  # Science & Technology
        },
        'status': {
            'privacyStatus': 'public',
            'embeddable': True
        }
    }
    
    try:
        # Initiate upload (non-blocking, async)
        request = youtube.videos().insert(
            part='snippet,status',
            body=body,
            media_body=media_upload
        )
        
        logger.info(f"Initiating YouTube upload: {task_id}")
        
        # Execute upload (can be monitored via resumable protocol)
        response = request.execute()
        
        video_id = response.get('id')
        youtube_url = f"https://www.youtube.com/watch?v={video_id}"
        
        logger.info(f"Upload successful: {youtube_url}")
        
        return {
            "task_id": task_id,
            "video_id": video_id,
            "status": "success",
            "youtube_url": youtube_url,
            "upload_progress_percent": 100.0
        }
    
    except Exception as e:
        logger.error(f"YouTube upload failed: {e}")
        return {
            "task_id": task_id,
            "video_id": None,
            "status": "failed",
            "youtube_url": None,
            "upload_progress_percent": 0.0,
            "error": str(e)
        }


def estimate_upload_time(file_size_mb: float, upload_speed_mbps: float = 1.0) -> float:
    """Estimate upload time (minutes) based on file size and connection speed.
    
    Typical: 100 MB video at 1 Mbps ~= 13 minutes.
    """
    if upload_speed_mbps <= 0:
        upload_speed_mbps = 1.0
    
    duration_minutes = (file_size_mb * 8) / (upload_speed_mbps * 60)
    return duration_minutes


if __name__ == "__main__":
    # Example usage
    print("YouTube API v3 Integration")
    print("Typical upload times (100 MB video):")
    for speed in [0.5, 1.0, 2.0, 5.0, 10.0]:
        minutes = estimate_upload_time(100, speed)
        print(f"  {speed} Mbps: {minutes:.1f} minutes")
